# Generated by Django 4.1.5 on 2023-02-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=300)),
                ('heading0', models.CharField(default='', max_length=150)),
                ('content0', models.CharField(default='', max_length=1000)),
                ('heading1', models.CharField(default='', max_length=150)),
                ('content1', models.CharField(default='', max_length=1000)),
                ('heading2', models.CharField(default='', max_length=150)),
                ('content2', models.CharField(default='', max_length=1000)),
                ('publish_date', models.DateField()),
                ('post_thumbnail', models.ImageField(default='', upload_to='blog/imgages')),
            ],
        ),
    ]
