# Generated by Django 4.1.5 on 2023-02-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content0',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content1',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content2',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
